language: java
addons:
  sonarcloud:
    organization: "williamsilva"
    token:
      secure: "d8be767bdd6178e551557811251ab13b06472871"
script:
  - mvn clean verify sonar:sonar -Pcoverage
notifications:
  email:
    recipients:
      - williamfincatti.dasilva@gmail.com
    on_success: always
    on_failure: always
