language: java
addons:
  sonarcloud:
    organization: "williamsilva"
    token:
      secure: "67431b3e297d64d397319e9b72ee4977a3d70754"
jdk:
  - openjdk8
script:
  - mvn clean verify sonar:sonar -Pcoverage
notifications:
  email:
    recipients:
      - williamfincatti.dasilva@gmail.com
    on_success: always
    on_failure: always
