language: java
addons:
  sonarcloud:
    organization: "williamsilva"
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
notifications:
  email:
    recipients:
      - williamfincatti.dasilva@gmail.com
    on_success: never
    on_failure: always
