language: java
addons:
  sonarcloud:
    organization: "williamsilva-github"
jdk:
  - openjdk8
script:
  - mvn clean verify
after_success:
  - mvn sonar:sonar
notifications:
  email:
    recipients:
      - williamfincatti.dasilva@gmail.com
    on_success: always
    on_failure: always