language: java
addons:
  sonarcloud:
    organization: "williamsilva"
    token:
      secure: "$SONAR_TOKEN"
script:
  - mvn clean install
notifications:
  email:
    recipients:
      - williamfincatti.dasilva@gmail.com
    on_success: always
    on_failure: always